server:
  port:  8085
spring:
  application:
    name: Workflow
  security:
    basic:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
        hibernate:
          format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ayushdaruka101@gmail.com
    password: qgte duxa gspp ftvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      INDENT_OUTPUT: true
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
#    display-request-duration: true